title: Allen Jeremy Uy
description: ""
baseurl: ""
url: "https://ajluy.github.io"

github_username: ajluy
linkedin_username: allen-jeremy-uy  # update with your LinkedIn slug

theme: minima
plugins: []